"""subscribers and fan-out

Revision ID: 07347b26efa0
Revises: 3e69336c3ffb
Create Date: 2026-09-25 22:19:54.139838
"""

import sqlalchemy as sa
from alembic import op

revision = "07347b26efa0"
down_revision = "3e69336c3ffb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscribers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=80), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=80), nullable=True),
        sa.Column(
            "status", sa.Enum("pending", "active", "past_due", "canceled", name="substatus"), nullable=False
        ),
        sa.Column("floor_margin_min", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("games", sa.JSON(), nullable=True),
        sa.Column("graders", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_terms_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("stripe_customer_id"),
    )
    op.create_table(
        "subscriber_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["subscribers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subscriber_id", "alert_id", name="uq_sub_alert"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriber_alerts")
    op.drop_table("subscribers")
    # ### end Alembic commands ###
