"""pack odds: measured tier value, sample size, stated ev

Revision ID: 08bae1423f2f
Revises: 07347b26efa0
Create Date: 2026-09-26 00:35:56.108999
"""

import sqlalchemy as sa
from alembic import op

revision = "08bae1423f2f"
down_revision = "07347b26efa0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pack_odds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("value_mean", sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column("sample_n", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("stated_ev", sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pack_odds", schema=None) as batch_op:
        batch_op.drop_column("stated_ev")
        batch_op.drop_column("sample_n")
        batch_op.drop_column("value_mean")

    # ### end Alembic commands ###
