"""alerts and trades

Revision ID: 3e69336c3ffb
Revises: ef5c13077a03
Create Date: 2026-09-25 22:14:08.766252
"""

import sqlalchemy as sa
from alembic import op

revision = "3e69336c3ffb"
down_revision = "ef5c13077a03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("floor_margin", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("market_margin", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("all_in_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("calculation", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("ix_alerts_listing_created", ["listing_id", "created_at"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("listing_ref", sa.String(length=200), nullable=True),
        sa.Column("source_key", sa.String(length=40), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("bought_at", sa.DateTime(), nullable=False),
        sa.Column("buy_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("buy_fees", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("intake_at", sa.DateTime(), nullable=True),
        sa.Column("intake_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("exit_kind", sa.Enum("open", "buyback", "sale", name="exitkind"), nullable=False),
        sa.Column("exit_at", sa.DateTime(), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("exit_fees", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("predicted_floor_margin", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("predicted_market_margin", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trades")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_listing_created")

    op.drop_table("alerts")
    # ### end Alembic commands ###
