"""pack odds pool size

Revision ID: 48b43089640f
Revises: 08bae1423f2f
Create Date: 2026-09-26 00:49:33.869556
"""

import sqlalchemy as sa
from alembic import op

revision = "48b43089640f"
down_revision = "08bae1423f2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pack_odds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pool_size", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pack_odds", schema=None) as batch_op:
        batch_op.drop_column("pool_size")

    # ### end Alembic commands ###
