"""phase 1 core tables

Revision ID: ca342c1e89c6
Revises:
Create Date: 2026-09-25 19:38:15.860593
"""

import sqlalchemy as sa
from alembic import op

revision = "ca342c1e89c6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_key", sa.String(length=300), nullable=False),
        sa.Column("game", sa.String(length=40), nullable=False),
        sa.Column("set_name", sa.String(length=160), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=True),
        sa.Column("variant", sa.String(length=120), nullable=True),
        sa.Column("grader", sa.String(length=20), nullable=True),
        sa.Column("grade_num", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_key"),
    )
    op.create_table(
        "match_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("left_kind", sa.String(length=20), nullable=False),
        sa.Column("left_id", sa.Integer(), nullable=False),
        sa.Column("right_kind", sa.String(length=20), nullable=False),
        sa.Column("right_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("verdict", sa.Enum("pending", "accepted", "rejected", name="verdict"), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("left_kind", "left_id", "right_kind", "right_id", name="uq_match_pair"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("chain", sa.String(length=20), nullable=True),
        sa.Column("license_status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "packs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("buyback_pct", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "slug", name="uq_pack_source_slug"),
    )
    op.create_table(
        "slabs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grader", sa.String(length=20), nullable=False),
        sa.Column("cert_number", sa.String(length=40), nullable=False),
        sa.Column("grade_label", sa.String(length=40), nullable=True),
        sa.Column("grade_num", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("cert_verified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grader", "cert_number", name="uq_slab_cert"),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("slab_id", sa.Integer(), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("ask_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Enum("active", "delisted", "sold", name="listingstatus"), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slab_id"],
            ["slabs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_listing_source_ext"),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index("ix_listing_status_seen", ["status", "last_seen"], unique=False)

    op.create_table(
        "pack_odds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pack_id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=60), nullable=False),
        sa.Column("probability", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("value_low", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("value_high", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("as_of", sa.DateTime(), nullable=False),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["packs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("slab_id", sa.Integer(), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("sold_at", sa.DateTime(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slab_id"],
            ["slabs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_sale_source_ext"),
    )
    op.create_table(
        "valuations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("slab_id", sa.Integer(), nullable=True),
        sa.Column(
            "value_type",
            sa.Enum(
                "platform_fmv", "buyback", "insured_value", "licensed_mid", "onchain_median", name="valuetype"
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("as_of", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slab_id"],
            ["slabs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuations", schema=None) as batch_op:
        batch_op.create_index("ix_valuation_lookup", ["card_id", "value_type", "as_of"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("valuations", schema=None) as batch_op:
        batch_op.drop_index("ix_valuation_lookup")

    op.drop_table("valuations")
    op.drop_table("sales")
    op.drop_table("pack_odds")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index("ix_listing_status_seen")

    op.drop_table("listings")
    op.drop_table("slabs")
    op.drop_table("packs")
    op.drop_table("sources")
    op.drop_table("match_candidates")
    op.drop_table("cards")
    # ### end Alembic commands ###
