"""ingest runs, cursors, onchain events

Revision ID: ef5c13077a03
Revises: ca342c1e89c6
Create Date: 2026-09-25 21:41:41.514766
"""

import sqlalchemy as sa
from alembic import op

revision = "ef5c13077a03"
down_revision = "ca342c1e89c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_cursors",
        sa.Column("source_key", sa.String(length=40), nullable=False),
        sa.Column("cursor", sa.String(length=200), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("source_key"),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Enum("ok", "error", "skipped", name="runstatus"), nullable=False),
        sa.Column("fetched", sa.Integer(), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("raw_path", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingest_runs", schema=None) as batch_op:
        batch_op.create_index("ix_ingest_runs_source_started", ["source_key", "started_at"], unique=False)

    op.create_table(
        "onchain_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=40), nullable=False),
        sa.Column("chain", sa.String(length=20), nullable=False),
        sa.Column("tx_hash", sa.String(length=120), nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("token_ref", sa.String(length=120), nullable=True),
        sa.Column("counterparty", sa.String(length=120), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=16), nullable=True),
        sa.Column("memo", sa.String(length=300), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "tx_hash", "log_index", name="uq_onchain_event"),
    )
    with op.batch_alter_table("onchain_events", schema=None) as batch_op:
        batch_op.create_index("ix_onchain_kind_ts", ["source_key", "kind", "occurred_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("onchain_events", schema=None) as batch_op:
        batch_op.drop_index("ix_onchain_kind_ts")

    op.drop_table("onchain_events")
    with op.batch_alter_table("ingest_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_ingest_runs_source_started")

    op.drop_table("ingest_runs")
    op.drop_table("ingest_cursors")
    # ### end Alembic commands ###
